Fix for the "Error: Cannot find module '../build/Debug/conpty_console_list.node'" error.
It was:

node:internal/modules/cjs/loader:1411
  throw err;
  ^

Error: Cannot find module '../build/Debug/conpty_console_list.node'
Require stack:
- c:\projects\arp\work\aroma-2\electron-app\lib\backend\conpty_console_list_agent.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1408:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1064:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1069:22)
    at Module._load (node:internal/modules/cjs/loader:1218:37)
    at c._load (node:electron/js2c/node_init:2:18013)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
    at Module.require (node:internal/modules/cjs/loader:1494:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (c:\projects\arp\work\aroma-2\electron-app\lib\backend\conpty_console_list_agent.js:14:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\projects\\arp\\work\\aroma-2\\electron-app\\lib\\backend\\conpty_console_list_agent.js'
  ]
}